name: hr_backend_app
description: An empty Aqueduct application.
version: 0.0.1
author: stable|kernel <jobs@stablekernel.com>

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  aqueduct: ^4.0.0-b1
  string_validator: ^0.1.4
  crypto: ^2.1.5
  jaguar_jwt: ^2.1.6

dev_dependencies:
  test: ^1.0.0
  aqueduct_test: ^2.0.0-b1